theme: jekyll-theme-cayman
title: TRANSLATIONAL RESEARCH IN MEDICAL ROBOTICS From Lab Bench to Clinical Use
description: May 17th workshop  |  IEEE International Conference on Robotics and Automation (ICRA 2024)
 
